library(RCIndex)
dir = "~/LLVM4.0/clang+llvm-4.0.0-x86_64-apple-darwin"
dir = "~/LLVM/clang+llvm-8.0.0-x86_64-apple-darwin"
dir = "~/LLVM/clang+llvm-10.0.0-x86_64-apple-darwin"
dir = '~/local'
stopifnot(file.exists(dir))
version = c(11, 0)

sysdir = system("xcrun --show-sdk-path", intern = TRUE)
cu = createTU(sprintf("%s/include/clang-c/Index.h", dir), include = c(sprintf("%s/include", dir), file.path(sysdir, "usr/include")))



enums = getEnums(cu, "clang-c")


library(RCodeGen)

cat(sprintf("# Autogenerated %s", Sys.Date()),
    sprintf("if(all(clangVersionNum(libclangVersion_Install) == c(%d, %d))) {", version[1], version[2]),
    unlist(lapply(enums, makeEnumClass)),
    file = sprintf("../R/a_enumDefs_%d.%d.R", version[1], version[2]),
    "}",
    sep = "\n\n")

