library(RCIndex)
dir = "~/LLVM4.0/clang+llvm-4.0.0-x86_64-apple-darwin"
version = c(4, 0)
cu = createTU(sprintf("%s/include/clang-c/Index.h", dir), include = sprintf("%s/include", dir))

enums = getEnums(cu)

library(RCodeGen)

cat(sprintf("# Autogenerated %s", Sys.Date()),
    sprintf("if(all(clangVersionNum(libclangVersion_Install) == c(%d, %d))) {", version[1], version[2]),
    unlist(lapply(enums, makeEnumClass)),
    file = sprintf("../R/a_enumDefs_%d.%d.R", version[1], version[2]),
    "}",
    sep = "\n\n")

